### ISSUE TITLE
数组

### ISSUE THREAD

**Issue by RogerDTZ** [RogerDTZ/rogerdtz.github.io#7]
https://rogerdtz.github.io/2018/09/28/%E6%95%B0%E7%BB%84/#comments 

   DescriptionDescription　　给你一个数组，每个元素都有一个颜色。要求支持两种操作：　　修改某个元素的颜色。　　询问这个数组有多少个子区间内没有重复的颜色。　　（只是为了凑摘要）

**Comment by RogerDTZ** [comment]
# 好多巨佬啊

**Comment by RollingYoyoball** [comment]
orzorzdtz
